# Generated by Django 5.1.5 on 2025-01-26 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='categoria',
            field=models.CharField(choices=[('PRATOS', 'Pratos'), ('COPOS', 'Copos'), ('RECHAUD', 'Rechaud'), ('GARRAFAS', 'Garrafas'), ('TALHERES', 'Talheres'), ('VIDROS', 'Vidros'), ('TRAVESSAS', 'Travessas'), ('INOX', 'Inox'), ('LOUÇAS', 'Louças'), ('XÍCARAS', 'Xícaras'), ('PRATARIA', 'Prataria'), ('MADEIRA', 'Madeira'), ('PANELAS', 'Panelas'), ('TOALHAS', 'Toalhas'), ('EQUIPAMENTOS', 'Equipamentos')], default='', max_length=100),
        ),
    ]
