# Generated by Django 5.1.5 on 2025-01-27 02:13

import produto.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_produto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(blank=True, upload_to=produto.models.Produto.get_upload_to),
        ),
    ]
