# Generated by Django 5.1.5 on 2025-02-05 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0004_produto_quantidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='quantidade',
        ),
    ]
